name: ci

on:
  push:
    branches: [ "dev_digo" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: digo66/app_flask:${{ github.sha }}

      - name: Trigger squonk
        uses: informaticsmatters/trigger-ci-action@v1
        with:
          ci-owner: pes-lab
          ci-repository: flask-kustomize
          # ci-ref: refs/heads/dev-branch
          ci-name: argo deploy
          ci-user: ${{ vars.DOCKERHUB_USERNAME }}
          ci-user-token: ${{ secrets.WORKFLOW_TOKEN }}  
